# Site settings
title: Aprendiz de Viajeiro
email: rodbusta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Página pessoal de Rodrigo Bustamante Magalhães.
  Brasileiro, engenheiro de computação - desenvolvedor web, vegetariano, feminista, entre outras coisas.  
#"Por um mundo onde sejamos socialmente iguais, humanamente diferentes e totalmente livres."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rodrigobusta.webfactional.com" # the base hostname & protocol for your site
twitter_username: rodrigobusta
github_username:  rodrigobusta

#-- 
permalink: 	'/blog/:year/:title/'
paginate_path: '/blog/page:num/'

# --
include: ['_pages']
relative_permalinks: false

# Build settings
markdown: kramdown
